### PR TITLE
Support pnpm package manager

### PR DESCRIPTION
**Pull request by jakub791**
- Explicitly installed `@vue/runtime-dom` so the type augmentations work as expected.
- Replaced all occurences of `isArray` function from `@vue/shared` with `Array.isArray`.
- Changed import of `computed` from `@vue/reacivity` to import from `vue`.

I added the 2 new eslint ignore comments because eslint was complaining without them.
The change to vite config is, uh, from a commit which was on this repo but I forgot about it. It dosen't break anything throught so might as well just leave it there.

### CODE REVIEW

**Comment by thepaperpilot** [comment]
I'm about to test this locally. In the meantime, would you like to add yourself to the contributors list in the changelog? Otherwise I can after the PR gets merged.

**Comment by thepaperpilot** [comment]
Can you update package-lock.json since you modified the dependencies?

**Comment by thepaperpilot** [comment]
I cannot build off this branch:
```
$ npm run build

> profectus@0.5.2 build
> vue-tsc --noEmit && vite build

src/App.vue(30,30): error TS2352: Conversion of type 'ThemeVars' to type 'CSSProperties' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
src/features/achievements/achievement.tsx(183,9): error TS2322: Type 'ComputedRef<boolean | Visibility>' is not assignable to type '(Computable<boolean | Visibility> | undefined) & (T & Partial<BaseAchievement> & ThisType<T & { visibility: ProcessedComputable<boolean | Visibility>; showPopups: ProcessedComputable<boolean>; } & Omit<Achievement<AchievementOptions>, "visibility" | "showPopups">>)["visibility"]'.
  Type 'ComputedRef<boolean | Visibility>' is not assignable to type 'Ref<boolean | Visibility> & (T & Partial<BaseAchievement> & ThisType<T & { visibility: ProcessedComputable<boolean | Visibility>; showPopups: ProcessedComputable<boolean>; } & Omit<Achievement<AchievementOptions>, "visibility" | "showPopups">>)["visibility"]'.
    Property '[RefSymbol]' is missing in type 'ComputedRef<boolean | Visibility>' but required in type 'Ref<boolean | Visibility>'.
```

**Comment by thepaperpilot** [comment]
Fails to build:
```
$ npm run build

> profectus@0.5.2 build
> vue-tsc --noEmit && vite build

src/App.vue(30,30): error TS2352: Conversion of type 'ThemeVars' to type 'CSSProperties' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

**Comment by jakub791** [comment]
> Can you update package-lock.json since you modified the dependencies?

Oh, npm didn't update it? Sure.

**Comment by jakub791** [comment]
Done.

**Comment by jakub791** [comment]
> Fails to build:
> 
> ```
> $ npm run build
> 
> > profectus@0.5.2 build
> > vue-tsc --noEmit && vite build
> 
> src/App.vue(30,30): error TS2352: Conversion of type 'ThemeVars' to type 'CSSProperties' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
> ```

Huh? I didn't update any dependencies.

**Comment by jakub791** [comment]
Hmm, I actually got the issuse now so I will fix that too.

**Comment by jakub791** [comment]
Ok, I got no errors when I tried to build the project localy

**Pull request closed without merging**
